data_processing:
    processing_params:

        shipments:
            fill_method: 'nearest'
            n_zeros: 12
            percentile: 0.05

        holidays:
            test: 1

        promotions:
            test: 2


data_science:
    model_options:
        features: None
        test_size: 0.2
        random_state: 42